version: "3.9"
services:
  couchdb:
    image: couchdb
    container_name: couchdb
    hostname: couchdb
    ports:
      - "5984:5984"
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    environment:
      - COUCHDB_USER=jkdfnf
      - COUCHDB_PASSWORD=@parta202D
    restart: unless-stopped
